--- #YAML:1.0
name:               Lexical-Types
version:            0.01
abstract:           Extend the semantics of typed lexicals.
author:
    - Vincent Pit <perl@profvince.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Carp:      0
    perl:      5.008
    XSLoader:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Lexical-Types
    homepage:    http://search.cpan.org/dist/Lexical-Types/
    license:     http://dev.perl.org/licenses/
    repository:  http://git.profvince.com/perl/modules/Lexical-Types.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
